
title: Co0lster
description: Web // Algorithms // Technology



markdown: kramdown
permalink: pretty

port: 8000



sass:
  sass_dir: assets/css
  style: :nested

url: http://127.0.0.1:8000/

gems:
  - jemoji
