
title: Co0lster
description: Web // Algorithms // Technology



markdown: kramdown
permalink: pretty

port: 8000



sass:
  sass_dir: assets/css
  style: :nested

url: http://www.co0lster.github.com/

gems:
  - jemoji
